# --- Stage 1: Build ---

FROM node:25-alpine AS builder

WORKDIR /app

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./ 

RUN npm install

COPY . .

RUN npm run build

# --- Stage 2: Prod ---

FROM nginx:stable-alpine

COPY --from=builder --chown=nginx:nginx /app/dist /usr/share/nginx/html
COPY --chown=nginx:nginx ./nginx/nginx.conf /etc/nginx/nginx.conf

RUN chown -R nginx:nginx /var/log/nginx /var/cache/nginx /var/run /etc/nginx

USER nginx 

EXPOSE 8080 8443

ENTRYPOINT [ "nginx" ]
CMD [ "-g", "daemon off;"]